# Generated by Django 3.0.8 on 2020-07-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
